--- 
- name: configure mpi 
  hosts: all
  gather_facts: no
  
  roles:
    - {role: grouped_passwordless_access, master_node: "master"}

  tasks:
    - name: installing necessary packages
      become: true
      apt:
        name:
          - build-essential
          - gcc-multilib
          - openmpi-bin
          - openmpi-doc
          - libopenmpi-dev
        state: latest
    - name: configure hosts file for the master
      become: yes
      copy:
        src: "hosts"
        dest: "/etc/hosts"
      notify:
        - restart networking
  handlers:
    - name: restart networking
      become: yes
      service: 
        name: "networking"
        state: "restarted"